name: General Verification and Pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  cancel-in-progress: ${{ forgejo.event_name != 'push' }}

jobs:
  if-not-on-weblate-branch:
    name: Check if not on weblate branch
    if: forgejo.head_ref != 'weblate'
    uses: ./.forgejo/workflows/verification-and-pages.yaml
