name: Pages

on:
  push:
    branches:
      - main
    paths:
      - '.forgejo/workflows/pages.yaml'
      - '**/pubspec.yaml'
      - '**/pubspec.lock'
      - 'packages/rrule_picker/lib/**'
      - 'packages/rrule_picker_example/lib/**'
      - 'packages/rrule_picker_example/web/**'

env:
  ACTIONS_CHECKOUT_VERSION: df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
  ACTIONS_GIT_PAGES_VERSION: f22fa1240d3ca8a869468f08fe702d54520eafd2 # v2
  FLUTTER_VERSION: sha256:46691e311715845de03a3ba4753a475476936805b29431b1f00f1816981033f8 # 3.44.0

jobs:
  pages:
    name: Build example web app and publish to git-pages
    runs-on: codeberg-small-lazy
    container:
      image: ghcr.io/cirruslabs/flutter@${{ env.FLUTTER_VERSION }}
    steps:
      - name: Install Node.js
        run: |
          apt-get update
          apt-get --yes install --no-install-recommends --no-install-suggests nodejs
      - name: Clone repository
        uses: https://data.forgejo.org/actions/checkout@${{ env.ACTIONS_CHECKOUT_VERSION }}
      - name: Get packages
        run: flutter pub get
      - name: Build example web app
        run: |
          flutter build web \
            --no-pub \
            --no-wasm-dry-run \
            --build-number '${{ forgejo.run_number }}' \
            --build-name '${{ forgejo.event.pull_request.head.sha || forgejo.sha }}' \
            --base-href '/${{ forgejo.event.repository.name }}/' \
            --csp \
            --release
        working-directory: packages/rrule_picker_example
      - name: Publish to git-pages
        uses: https://data.forgejo.org/actions/git-pages@${{ env.ACTIONS_GIT_PAGES_VERSION }}
        with:
          site: https://${{ forgejo.repository_owner }}.codeberg.page/${{ forgejo.event.repository.name }}/
          token: ${{ forgejo.token }}
          source: packages/rrule_picker_example/build/web/
