name: rrule_picker
description: RRULE picker widget.
version: 0.0.1
homepage: https://codeberg.org/0rzech/rrule_picker
repository: https://codeberg.org/0rzech/rrule_picker/src/branch/main/packages/rrule_picker
issue_tracker: https://codeberg.org/0rzech/rrule_picker/issues

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '>=0.20.2 <1.0.0'

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  kiri_check: ^1.3.1
  mocktail: ^1.0.5
  spot: ^0.18.0

flutter:
  generate: true
