name: rrule_picker
description: RRule picker widget.
version: 0.0.1
homepage: 'https://codeberg.org/0rzech/rrule_picker'

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  kiri_check: any
  spot: any

flutter:
  generate: true
