name: rrule_picker
description: RRULE picker is a widget used to manipulate RRULEs in accordance to a subset of RFC 5545.
version: 0.1.4
homepage: https://codeberg.org/0rzech/rrule_picker
repository: https://codeberg.org/0rzech/rrule_picker/src/branch/main/packages/rrule_picker
issue_tracker: https://codeberg.org/0rzech/rrule_picker/issues
screenshots:
  - description: Yearly recurrence (relative day).
    path: screenshots/yearly_relative.png
  - description: Yearly recurrence (precise day).
    path: screenshots/yearly_precise.png
  - description: Monthly recurrence (relative day).
    path: screenshots/monthly_relative.png
  - description: Monthly recurrence (precise day).
    path: screenshots/monthly_precise.png
  - description: Weekly recurrence.
    path: screenshots/weekly.png
  - description: Daily recurrence.
    path: screenshots/daily.png
  - description: No recurrence.
    path: screenshots/never.png
topics:
  - flutter
  - material
  - picker
  - rrule
  - widget

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: '>=0.20.2 <1.0.0'

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  kiri_check: ^1.3.1
  mocktail: ^1.0.5
  spot: ^0.18.0

flutter:
  generate: true
