name: rrule_picker_example
description: An example RRulePicker app.
publish_to: none

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  cupertino_icons: any
  flutter:
    sdk: flutter
  material_ui: any
  rrule_picker: any
  url_launcher: any

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
