name: rrule_picker_example
description: An example RRulePicker app.
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rrule_picker: any

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
