name: Verification

on: workflow_call

jobs:
  verification:
    name: Verify

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gmeligio/flutter-web@sha256:d6122a04d19ba511c58fafcdabd45bce8b5c48331de4d19bcc6bcb89f49ee29e # 3.47.0

    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v7
      - name: Get packages
        run: flutter pub get
      - name: Generate l10n
        run: tool/flutter_gen_l10n.dart
      - name: Check for missing localizations
        run: tool/check_missing_localizations.dart
      - name: Check code formatting
        run: tool/dart_format.dart
      - name: Analyze code
        run: tool/flutter_analyze.dart --no-pub
      - name: Run tests in Dart VM
        run: tool/flutter_test.dart --no-pub --branch-coverage
      - name: Build example web app (feature branch only)
        if: >
          (github.head_ref || github.ref_name) != 'main' &&
          (github.head_ref || github.ref_name) != 'weblate'
        run: |
          flutter build web \
            --no-pub \
            --no-wasm-dry-run \
            --build-number '${{ github.run_number }}' \
            --build-name '${{ github.event.pull_request.head.sha || github.sha }}' \
            --base-href '/${{ github.event.repository.name }}/' \
            --csp \
            --release
        working-directory: packages/rrule_picker/example
